
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 25 2025 08:49:10 IST (Aug 25 2025 03:19:10 UTC)

// Verification Directory fv/four_bitcounter 

module four_bitcounter(clk, rst, q, SE, scan_in, scan_out);
  input clk, rst, SE, scan_in;
  output [3:0] q;
  output scan_out;
  wire clk, rst, SE, scan_in;
  wire [3:0] q;
  wire scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  assign scan_out = q[3];
  SDFFQX1 \q_reg[3] (.CK (clk), .D (n_9), .SI (q[2]), .SE (SE), .Q
       (q[3]));
  SDFFQX1 \q_reg[2] (.CK (clk), .D (n_8), .SI (q[1]), .SE (SE), .Q
       (q[2]));
  NOR2XL g84__2398(.A (rst), .B (n_7), .Y (n_9));
  SDFFQX1 \q_reg[1] (.CK (clk), .D (n_3), .SI (q[0]), .SE (SE), .Q
       (q[1]));
  NOR2XL g88__5107(.A (rst), .B (n_6), .Y (n_8));
  AOI21XL g86__6260(.A0 (q[3]), .A1 (n_5), .B0 (n_4), .Y (n_7));
  OAI21X1 g90__4319(.A0 (q[2]), .A1 (n_2), .B0 (n_5), .Y (n_6));
  NOR2XL g87__8428(.A (q[3]), .B (n_5), .Y (n_4));
  SDFFQX1 \q_reg[0] (.CK (clk), .D (n_1), .SI (scan_in), .SE (SE), .Q
       (q[0]));
  NOR3X1 g92__5526(.A (rst), .B (n_0), .C (n_2), .Y (n_3));
  NAND2XL g91__6783(.A (q[2]), .B (n_2), .Y (n_5));
  NOR2XL g94__3680(.A (rst), .B (q[0]), .Y (n_1));
  NOR2XL g95__1617(.A (q[0]), .B (q[1]), .Y (n_0));
  AND2X1 g96__2802(.A (q[1]), .B (q[0]), .Y (n_2));
endmodule

