
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug  4 2025 09:08:39 IST (Aug  4 2025 03:38:39 UTC)

// Verification Directory fv/four_bitcounter 

module four_bitcounter(clk, rst, q);
  input clk, rst;
  output [3:0] q;
  wire clk, rst;
  wire [3:0] q;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  DFFQX1 \q_reg[3] (.CK (clk), .D (n_9), .Q (q[3]));
  NOR2XL g84__2398(.A (rst), .B (n_7), .Y (n_9));
  DFFQX1 \q_reg[2] (.CK (clk), .D (n_8), .Q (q[2]));
  NOR2XL g88__5107(.A (rst), .B (n_6), .Y (n_8));
  AOI21XL g86__6260(.A0 (q[3]), .A1 (n_5), .B0 (n_4), .Y (n_7));
  DFFQX1 \q_reg[1] (.CK (clk), .D (n_3), .Q (q[1]));
  OAI21X1 g90__4319(.A0 (q[2]), .A1 (n_2), .B0 (n_5), .Y (n_6));
  NOR2XL g87__8428(.A (q[3]), .B (n_5), .Y (n_4));
  NOR3X1 g92__5526(.A (rst), .B (n_0), .C (n_2), .Y (n_3));
  DFFQX1 \q_reg[0] (.CK (clk), .D (n_1), .Q (q[0]));
  NAND2XL g91__6783(.A (q[2]), .B (n_2), .Y (n_5));
  NOR2XL g94__3680(.A (rst), .B (q[0]), .Y (n_1));
  NOR2XL g95__1617(.A (q[0]), .B (q[1]), .Y (n_0));
  AND2X1 g96__2802(.A (q[1]), .B (q[0]), .Y (n_2));
endmodule

