
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  2 2025 16:25:44 IST (Sep  2 2025 10:55:44 UTC)

// Verification Directory fv/sync_HA 

module sync_HA(a, b, clk, sum, c_out, SE, scan_in, scan_out);
  input a, b, clk, SE, scan_in;
  output sum, c_out, scan_out;
  wire a, b, clk, SE, scan_in;
  wire sum, c_out, scan_out;
  wire n_0, n_1;
  assign scan_out = sum;
  SDFFQX1 sum_reg(.CK (clk), .D (n_1), .SI (c_out), .SE (SE), .Q (sum));
  SDFFQX1 c_out_reg(.CK (clk), .D (n_0), .SI (scan_in), .SE (SE), .Q
       (c_out));
  ADDHXL g42__2398(.A (b), .B (a), .CO (n_0), .S (n_1));
endmodule

