
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  5 2025 16:38:22 IST (Sep  5 2025 11:08:22 UTC)

// Verification Directory fv/simple_processor 

module simple_processor(clk, rst_n, start, op_sel, in_a, in_b, result,
     done, SE, scan_in, scan_out);
  input clk, rst_n, start, op_sel, SE, scan_in;
  input [7:0] in_a, in_b;
  output [7:0] result;
  output done, scan_out;
  wire clk, rst_n, start, op_sel, SE, scan_in;
  wire [7:0] in_a, in_b;
  wire [7:0] result;
  wire done, scan_out;
  wire [7:0] reg_a;
  wire [7:0] reg_b;
  wire [1:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57;
  SDFFRHQX1 \result_reg[7] (.RN (rst_n), .CK (clk), .D (n_57), .SI
       (result[6]), .SE (SE), .Q (result[7]));
  MX2X1 g1312__2398(.A (n_56), .B (result[7]), .S0 (n_54), .Y (n_57));
  SDFFRHQX1 \result_reg[6] (.RN (rst_n), .CK (clk), .D (n_55), .SI
       (result[5]), .SE (SE), .Q (result[6]));
  OAI21X1 g1314__5107(.A0 (n_52), .A1 (n_51), .B0 (n_53), .Y (n_56));
  MX2X1 g1315__6260(.A (n_50), .B (result[6]), .S0 (n_54), .Y (n_55));
  NAND2XL g1316__4319(.A (n_52), .B (n_51), .Y (n_53));
  SDFFRHQX1 \result_reg[5] (.RN (rst_n), .CK (clk), .D (n_49), .SI
       (result[4]), .SE (SE), .Q (result[5]));
  ADDFXL g1317__8428(.A (reg_a[6]), .B (n_5), .CI (n_47), .CO (n_51),
       .S (n_50));
  MX2X1 g1319__5526(.A (n_48), .B (result[5]), .S0 (n_54), .Y (n_49));
  SDFFRHQX1 \result_reg[4] (.RN (rst_n), .CK (clk), .D (n_46), .SI
       (result[3]), .SE (SE), .Q (result[4]));
  ADDFX1 g1320__6783(.A (n_7), .B (reg_a[5]), .CI (n_44), .CO (n_47),
       .S (n_48));
  MX2X1 g1322__3680(.A (n_45), .B (result[4]), .S0 (n_54), .Y (n_46));
  SDFFRHQX1 \result_reg[3] (.RN (rst_n), .CK (clk), .D (n_43), .SI
       (result[2]), .SE (SE), .Q (result[3]));
  ADDFX1 g1323__1617(.A (n_8), .B (reg_a[4]), .CI (n_41), .CO (n_44),
       .S (n_45));
  MX2X1 g1325__2802(.A (n_42), .B (result[3]), .S0 (n_54), .Y (n_43));
  SDFFRHQX1 \result_reg[2] (.RN (rst_n), .CK (clk), .D (n_40), .SI
       (result[1]), .SE (SE), .Q (result[2]));
  ADDFX1 g1326__1705(.A (n_6), .B (reg_a[3]), .CI (n_38), .CO (n_41),
       .S (n_42));
  MX2X1 g1328__5122(.A (n_39), .B (result[2]), .S0 (n_54), .Y (n_40));
  SDFFRHQX1 \result_reg[1] (.RN (rst_n), .CK (clk), .D (n_37), .SI
       (result[0]), .SE (SE), .Q (result[1]));
  ADDFX1 g1329__8246(.A (n_10), .B (reg_a[2]), .CI (n_35), .CO (n_38),
       .S (n_39));
  MX2X1 g1331__7098(.A (n_36), .B (result[1]), .S0 (n_54), .Y (n_37));
  SDFFRHQX1 \result_reg[0] (.RN (rst_n), .CK (clk), .D (n_34), .SI
       (reg_b[7]), .SE (SE), .Q (result[0]));
  SDFFRHQX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_31), .SI
       (result[7]), .SE (SE), .Q (state[0]));
  ADDFX1 g1332__6131(.A (n_11), .B (reg_a[1]), .CI (n_1), .CO (n_35),
       .S (n_36));
  SDFFRHQX1 \reg_a_reg[1] (.RN (rst_n), .CK (clk), .D (n_21), .SI
       (reg_a[0]), .SE (SE), .Q (reg_a[1]));
  SDFFRHQX1 \reg_a_reg[5] (.RN (rst_n), .CK (clk), .D (n_14), .SI
       (reg_a[4]), .SE (SE), .Q (reg_a[5]));
  SDFFRHQX1 \reg_b_reg[1] (.RN (rst_n), .CK (clk), .D (n_20), .SI
       (reg_b[0]), .SE (SE), .Q (reg_b[1]));
  SDFFRHQX1 \reg_a_reg[2] (.RN (rst_n), .CK (clk), .D (n_24), .SI
       (reg_a[1]), .SE (SE), .Q (reg_a[2]));
  SDFFRHQX1 \reg_b_reg[3] (.RN (rst_n), .CK (clk), .D (n_27), .SI
       (reg_b[2]), .SE (SE), .Q (reg_b[3]));
  SDFFRHQX1 \reg_b_reg[4] (.RN (rst_n), .CK (clk), .D (n_26), .SI
       (reg_b[3]), .SE (SE), .Q (reg_b[4]));
  SDFFRHQX1 \reg_b_reg[6] (.RN (rst_n), .CK (clk), .D (n_22), .SI
       (reg_b[5]), .SE (SE), .Q (reg_b[6]));
  SDFFRHQX1 \reg_b_reg[7] (.RN (rst_n), .CK (clk), .D (n_12), .SI
       (reg_b[6]), .SE (SE), .Q (reg_b[7]));
  SDFFRHQX1 \reg_a_reg[7] (.RN (rst_n), .CK (clk), .D (n_19), .SI
       (reg_a[6]), .SE (SE), .Q (reg_a[7]));
  SDFFRHQX1 \reg_b_reg[2] (.RN (rst_n), .CK (clk), .D (n_29), .SI
       (reg_b[1]), .SE (SE), .Q (reg_b[2]));
  SDFFRHQX1 \reg_b_reg[5] (.RN (rst_n), .CK (clk), .D (n_25), .SI
       (reg_b[4]), .SE (SE), .Q (reg_b[5]));
  SDFFRHQX1 \reg_a_reg[4] (.RN (rst_n), .CK (clk), .D (n_30), .SI
       (reg_a[3]), .SE (SE), .Q (reg_a[4]));
  SDFFRHQX1 \reg_a_reg[6] (.RN (rst_n), .CK (clk), .D (n_13), .SI
       (reg_a[5]), .SE (SE), .Q (reg_a[6]));
  SDFFRHQX1 \reg_a_reg[3] (.RN (rst_n), .CK (clk), .D (n_23), .SI
       (reg_a[2]), .SE (SE), .Q (reg_a[3]));
  SDFFRHQX1 done_reg(.RN (rst_n), .CK (clk), .D (n_17), .SI (scan_in),
       .SE (SE), .Q (done));
  SDFFRHQX1 \reg_b_reg[0] (.RN (rst_n), .CK (clk), .D (n_16), .SI
       (reg_a[7]), .SE (SE), .Q (reg_b[0]));
  SDFFRHQX1 \reg_a_reg[0] (.RN (rst_n), .CK (clk), .D (n_15), .SI
       (done), .SE (SE), .Q (reg_a[0]));
  SDFFRHQX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_18), .SI
       (state[0]), .SE (SE), .Q (scan_out));
  OAI21X1 g1345__1881(.A0 (reg_a[7]), .A1 (n_32), .B0 (n_33), .Y
       (n_52));
  MX2X1 g1334__5115(.A (n_4), .B (result[0]), .S0 (n_54), .Y (n_34));
  NAND2XL g1356__7482(.A (reg_a[7]), .B (n_32), .Y (n_33));
  OAI2BB1X1 g1359__4733(.A0N (start), .A1N (n_2), .B0 (n_54), .Y
       (n_31));
  MX2X1 g1374__6161(.A (reg_a[4]), .B (in_a[4]), .S0 (n_28), .Y (n_30));
  MX2X1 g1367__9315(.A (reg_b[2]), .B (in_b[2]), .S0 (n_28), .Y (n_29));
  MX2X1 g1368__9945(.A (reg_b[3]), .B (in_b[3]), .S0 (n_28), .Y (n_27));
  MX2X1 g1369__2883(.A (reg_b[4]), .B (in_b[4]), .S0 (n_28), .Y (n_26));
  MX2X1 g1370__2346(.A (reg_b[5]), .B (in_b[5]), .S0 (n_28), .Y (n_25));
  MX2X1 g1371__1666(.A (reg_a[2]), .B (in_a[2]), .S0 (n_28), .Y (n_24));
  MX2X1 g1372__7410(.A (reg_a[3]), .B (in_a[3]), .S0 (n_28), .Y (n_23));
  MX2X1 g1373__6417(.A (reg_b[6]), .B (in_b[6]), .S0 (n_28), .Y (n_22));
  MX2X1 g1366__5477(.A (reg_a[1]), .B (in_a[1]), .S0 (n_28), .Y (n_21));
  MX2X1 g1365__2398(.A (reg_b[1]), .B (in_b[1]), .S0 (n_28), .Y (n_20));
  MX2X1 g1363__5107(.A (reg_a[7]), .B (in_a[7]), .S0 (n_28), .Y (n_19));
  OAI2BB1XL g1357__6260(.A0N (state[0]), .A1N (n_0), .B0 (n_54), .Y
       (n_18));
  OAI2BB1X1 g1358__4319(.A0N (done), .A1N (state[0]), .B0 (n_3), .Y
       (n_17));
  MX2X1 g1364__8428(.A (reg_b[0]), .B (in_b[0]), .S0 (n_28), .Y (n_16));
  MX2X1 g1360__5526(.A (reg_a[0]), .B (in_a[0]), .S0 (n_28), .Y (n_15));
  MX2X1 g1361__6783(.A (reg_a[5]), .B (in_a[5]), .S0 (n_28), .Y (n_14));
  MX2X1 g1362__3680(.A (reg_a[6]), .B (in_a[6]), .S0 (n_28), .Y (n_13));
  MX2X1 g1375__1617(.A (reg_b[7]), .B (in_b[7]), .S0 (n_28), .Y (n_12));
  MXI2XL g1378__2802(.A (n_9), .B (op_sel), .S0 (reg_b[1]), .Y (n_11));
  MXI2XL g1379__1705(.A (n_9), .B (op_sel), .S0 (reg_b[2]), .Y (n_10));
  MXI2XL g1380__5122(.A (n_9), .B (op_sel), .S0 (reg_b[4]), .Y (n_8));
  MXI2XL g1383__8246(.A (n_9), .B (op_sel), .S0 (reg_b[5]), .Y (n_7));
  MXI2XL g1382__7098(.A (n_9), .B (op_sel), .S0 (reg_b[3]), .Y (n_6));
  MXI2XL g1381__6131(.A (n_9), .B (op_sel), .S0 (reg_b[6]), .Y (n_5));
  MXI2XL g1384__1881(.A (n_9), .B (op_sel), .S0 (reg_b[7]), .Y (n_32));
  XOR2XL g1376__5115(.A (reg_a[0]), .B (reg_b[0]), .Y (n_4));
  OAI21X1 g1377__7482(.A0 (done), .A1 (state[0]), .B0 (scan_out), .Y
       (n_3));
  INVXL g1386(.A (n_28), .Y (n_2));
  MX2X1 g1348__4733(.A (op_sel), .B (reg_a[0]), .S0 (reg_b[0]), .Y
       (n_1));
  NOR2BX1 g1388__6161(.AN (state[0]), .B (scan_out), .Y (n_28));
  NAND2BXL g1385__9315(.AN (start), .B (scan_out), .Y (n_0));
  NAND2BX1 g1387__9945(.AN (state[0]), .B (scan_out), .Y (n_54));
  CLKINVX1 g1389(.A (op_sel), .Y (n_9));
endmodule

