
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 11 2025 12:29:27 IST (Aug 11 2025 06:59:27 UTC)

// Verification Directory fv/sync_FA 

module sync_FA(a, b, cin, clk, sum, cout);
  input a, b, cin, clk;
  output sum, cout;
  wire a, b, cin, clk;
  wire sum, cout;
  wire c1_wire, c2_wire, n_0, s1_wire, sum_w;
  sync_HA ha1(.a (a), .b (b), .clk (clk), .sum (s1_wire), .c_out
       (c1_wire));
  sync_HA ha2(.a (s1_wire), .b (cin), .clk (clk), .sum (sum_w), .c_out
       (c2_wire));
  DFFQXL cout_reg(.CK (clk), .D (n_0), .Q (cout));
  DFFQXL sum_reg(.CK (clk), .D (sum_w), .Q (sum));
  OR2X1 g17__2398(.A (c1_wire), .B (c2_wire), .Y (n_0));
endmodule

