
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  2 2025 16:41:40 IST (Sep  2 2025 11:11:40 UTC)

// Verification Directory fv/sr_ff 

module sr_ff(S, R, clk, Q, Q_bar, SE, scan_in, scan_out);
  input S, R, clk, SE, scan_in;
  output Q, Q_bar, scan_out;
  wire S, R, clk, SE, scan_in;
  wire Q, Q_bar, scan_out;
  wire n_0, n_1, n_2;
  assign scan_out = Q;
  SDFFQX1 Q_reg(.CK (clk), .D (n_2), .SI (Q_bar), .SE (SE), .Q (Q));
  SMDFFHQX1 Q_bar_reg(.CK (clk), .D0 (R), .D1 (n_1), .S0 (n_0), .SI
       (scan_in), .SE (SE), .Q (Q_bar));
  MXI2XL g25__2398(.A (R), .B (n_1), .S0 (n_0), .Y (n_2));
  NOR2XL g26__5107(.A (R), .B (S), .Y (n_0));
  CLKINVX1 g27(.A (Q), .Y (n_1));
endmodule

