
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  5 2025 15:16:08 IST (Sep  5 2025 09:46:08 UTC)

// Verification Directory fv/booth_multiplier 

module booth_multiplier(clk, rst_n, start, multiplicand, multiplier,
     done, product, SE, scan_in, scan_out);
  input clk, rst_n, start, SE, scan_in;
  input [7:0] multiplicand, multiplier;
  output done, scan_out;
  output [15:0] product;
  wire clk, rst_n, start, SE, scan_in;
  wire [7:0] multiplicand, multiplier;
  wire done, scan_out;
  wire [15:0] product;
  wire [8:0] A;
  wire [4:0] count;
  wire [8:0] Q;
  wire [8:0] M;
  wire [2:0] state;
  wire Q_minus_1, n_0, n_1, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13, n_14, n_15, n_16;
  wire n_20, n_24, n_25, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_80, n_85, n_89, n_92;
  wire n_94, n_95, n_96, n_107, n_109, n_110, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_170, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201;
  SDFFRHQX1 \A_reg[8] (.RN (rst_n), .CK (clk), .D (n_150), .SI (A[7]),
       .SE (SE), .Q (A[8]));
  MX2X1 g3246__2398(.A (n_149), .B (A[8]), .S0 (n_147), .Y (n_150));
  SDFFRHQX1 \A_reg[7] (.RN (rst_n), .CK (clk), .D (n_148), .SI (A[6]),
       .SE (SE), .Q (A[7]));
  OAI21X1 g3248__5107(.A0 (n_34), .A1 (n_146), .B0 (n_144), .Y (n_149));
  MX2X1 g3249__6260(.A (n_145), .B (A[7]), .S0 (n_147), .Y (n_148));
  SDFFRHQX1 \A_reg[6] (.RN (rst_n), .CK (clk), .D (n_139), .SI (A[5]),
       .SE (SE), .Q (A[6]));
  AOI21XL g3252__4319(.A0 (n_142), .A1 (n_141), .B0 (n_143), .Y
       (n_146));
  OAI2BB1XL g3251__8428(.A0N (n_137), .A1N (n_140), .B0 (n_144), .Y
       (n_145));
  NOR2XL g3253__5526(.A (n_142), .B (n_141), .Y (n_143));
  ADDFXL g3255__6783(.A (A[7]), .B (n_61), .CI (n_135), .CO (n_141), .S
       (n_140));
  MXI2XL g3254__3680(.A (n_138), .B (n_7), .S0 (n_147), .Y (n_139));
  SDFFRHQX1 \A_reg[5] (.RN (rst_n), .CK (clk), .D (n_134), .SI (A[4]),
       .SE (SE), .Q (A[5]));
  AOI22X1 g3257__1617(.A0 (n_137), .A1 (n_136), .B0 (A[7]), .B1
       (n_132), .Y (n_138));
  ADDFX1 g3259__2802(.A (n_56), .B (A[6]), .CI (n_130), .CO (n_135), .S
       (n_136));
  MXI2XL g3258__1705(.A (n_133), .B (n_1), .S0 (n_147), .Y (n_134));
  SDFFRHQX1 \A_reg[4] (.RN (rst_n), .CK (clk), .D (n_129), .SI (A[3]),
       .SE (SE), .Q (A[4]));
  AOI22X1 g3261__5122(.A0 (n_137), .A1 (n_131), .B0 (A[6]), .B1
       (n_132), .Y (n_133));
  ADDFX1 g3263__8246(.A (n_57), .B (A[5]), .CI (n_126), .CO (n_130), .S
       (n_131));
  MXI2XL g3262__7098(.A (n_128), .B (n_3), .S0 (n_147), .Y (n_129));
  SDFFRHQX1 \A_reg[3] (.RN (rst_n), .CK (clk), .D (n_125), .SI (A[2]),
       .SE (SE), .Q (A[3]));
  AOI22X1 g3265__6131(.A0 (n_137), .A1 (n_127), .B0 (A[5]), .B1
       (n_132), .Y (n_128));
  ADDFX1 g3267__1881(.A (n_59), .B (A[4]), .CI (n_122), .CO (n_126), .S
       (n_127));
  MXI2XL g3266__5115(.A (n_124), .B (n_6), .S0 (n_147), .Y (n_125));
  SDFFRHQX1 \A_reg[2] (.RN (rst_n), .CK (clk), .D (n_121), .SI (A[1]),
       .SE (SE), .Q (A[2]));
  AOI22X1 g3269__7482(.A0 (n_137), .A1 (n_123), .B0 (A[4]), .B1
       (n_132), .Y (n_124));
  ADDFX1 g3271__4733(.A (n_45), .B (A[3]), .CI (n_118), .CO (n_122), .S
       (n_123));
  MXI2XL g3270__6161(.A (n_120), .B (n_5), .S0 (n_147), .Y (n_121));
  SDFFRHQX1 \A_reg[1] (.RN (rst_n), .CK (clk), .D (n_117), .SI (A[0]),
       .SE (SE), .Q (A[1]));
  AOI22X1 g3273__9315(.A0 (n_137), .A1 (n_119), .B0 (A[3]), .B1
       (n_132), .Y (n_120));
  ADDFX1 g3275__9945(.A (n_54), .B (A[2]), .CI (n_114), .CO (n_118), .S
       (n_119));
  MXI2XL g3274__2883(.A (n_116), .B (n_4), .S0 (n_147), .Y (n_117));
  SDFFRHQX1 \A_reg[0] (.RN (rst_n), .CK (clk), .D (n_113), .SI
       (scan_in), .SE (SE), .Q (A[0]));
  AOI22X1 g3277__2346(.A0 (n_137), .A1 (n_115), .B0 (A[2]), .B1
       (n_132), .Y (n_116));
  ADDFX1 g3281__1666(.A (n_35), .B (A[1]), .CI (n_109), .CO (n_114), .S
       (n_115));
  MXI2XL g3280__7410(.A (n_112), .B (n_85), .S0 (n_147), .Y (n_113));
  SDFFRHQX1 \count_reg[4] (.RN (rst_n), .CK (clk), .D (n_170), .SI
       (count[3]), .SE (SE), .Q (count[4]));
  SDFFRHQX1 \Q_reg[4] (.RN (rst_n), .CK (clk), .D (n_199), .SI (Q[3]),
       .SE (SE), .Q (Q[4]));
  SDFFRHQX1 \Q_reg[1] (.RN (rst_n), .CK (clk), .D (n_189), .SI (Q[0]),
       .SE (SE), .Q (Q[1]));
  SDFFRHQX1 \Q_reg[2] (.RN (rst_n), .CK (clk), .D (n_191), .SI (Q[1]),
       .SE (SE), .Q (Q[2]));
  SDFFRHQX1 \Q_reg[3] (.RN (rst_n), .CK (clk), .D (n_201), .SI (Q[2]),
       .SE (SE), .Q (Q[3]));
  SDFFRHQX1 \Q_reg[6] (.RN (rst_n), .CK (clk), .D (n_195), .SI (Q[5]),
       .SE (SE), .Q (Q[6]));
  SDFFRHQX1 \Q_reg[7] (.RN (rst_n), .CK (clk), .D (n_193), .SI (Q[6]),
       .SE (SE), .Q (Q[7]));
  SDFFRHQX1 \Q_reg[5] (.RN (rst_n), .CK (clk), .D (n_197), .SI (Q[4]),
       .SE (SE), .Q (Q[5]));
  SDFFRHQX1 \Q_reg[0] (.RN (rst_n), .CK (clk), .D (n_187), .SI
       (Q_minus_1), .SE (SE), .Q (Q[0]));
  AOI22X1 g3283__6417(.A0 (n_137), .A1 (n_110), .B0 (A[1]), .B1
       (n_132), .Y (n_112));
  SDFFRHQX1 Q_minus_1_reg(.RN (rst_n), .CK (clk), .D (n_179), .SI
       (M[7]), .SE (SE), .Q (Q_minus_1));
  SDFFRHQX1 \count_reg[3] (.RN (rst_n), .CK (clk), .D (n_180), .SI
       (count[2]), .SE (SE), .Q (count[3]));
  SDFFRHQX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_94), .SI
       (product[15]), .SE (SE), .Q (state[0]));
  SDFFRHQX1 \count_reg[2] (.RN (rst_n), .CK (clk), .D (n_181), .SI
       (count[1]), .SE (SE), .Q (count[2]));
  SDFFRHQX1 \Q_reg[8] (.RN (rst_n), .CK (clk), .D (n_182), .SI (Q[7]),
       .SE (SE), .Q (Q[8]));
  SDFFRHQX1 \count_reg[1] (.RN (rst_n), .CK (clk), .D (n_184), .SI
       (count[0]), .SE (SE), .Q (count[1]));
  SDFFRHQX1 \count_reg[0] (.RN (rst_n), .CK (clk), .D (n_183), .SI
       (Q[8]), .SE (SE), .Q (count[0]));
  SDFFRHQX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_80), .SI
       (state[0]), .SE (SE), .Q (state[1]));
  ADDFX1 g3286__2398(.A (n_60), .B (A[0]), .CI (n_55), .CO (n_109), .S
       (n_110));
  SDFFRHQX1 \M_reg[7] (.RN (rst_n), .CK (clk), .D (n_75), .SI (M[6]),
       .SE (SE), .Q (M[7]));
  SDFFRHQX1 \M_reg[1] (.RN (rst_n), .CK (clk), .D (n_73), .SI (M[0]),
       .SE (SE), .Q (M[1]));
  SDFFRHQX1 \M_reg[0] (.RN (rst_n), .CK (clk), .D (n_74), .SI (A[8]),
       .SE (SE), .Q (M[0]));
  SDFFRHQX1 \M_reg[6] (.RN (rst_n), .CK (clk), .D (n_68), .SI (M[5]),
       .SE (SE), .Q (M[6]));
  SDFFRHQX1 \M_reg[2] (.RN (rst_n), .CK (clk), .D (n_72), .SI (M[1]),
       .SE (SE), .Q (M[2]));
  SDFFRHQX1 \M_reg[4] (.RN (rst_n), .CK (clk), .D (n_70), .SI (M[3]),
       .SE (SE), .Q (M[4]));
  SDFFRHQX1 \M_reg[3] (.RN (rst_n), .CK (clk), .D (n_71), .SI (M[2]),
       .SE (SE), .Q (M[3]));
  SDFFRHQX1 \M_reg[5] (.RN (rst_n), .CK (clk), .D (n_69), .SI (M[4]),
       .SE (SE), .Q (M[5]));
  SDFFRHQX1 \state_reg[2] (.RN (rst_n), .CK (clk), .D (n_64), .SI
       (state[1]), .SE (SE), .Q (scan_out));
  SDFFRHQX1 \product_reg[9] (.RN (rst_n), .CK (clk), .D (n_36), .SI
       (product[8]), .SE (SE), .Q (product[9]));
  SDFFRHQX1 \product_reg[8] (.RN (rst_n), .CK (clk), .D (n_62), .SI
       (product[7]), .SE (SE), .Q (product[8]));
  SDFFRHQX1 \product_reg[0] (.RN (rst_n), .CK (clk), .D (n_47), .SI
       (done), .SE (SE), .Q (product[0]));
  SDFFRHQX1 \product_reg[2] (.RN (rst_n), .CK (clk), .D (n_33), .SI
       (product[1]), .SE (SE), .Q (product[2]));
  SDFFRHQX1 \product_reg[3] (.RN (rst_n), .CK (clk), .D (n_44), .SI
       (product[2]), .SE (SE), .Q (product[3]));
  SDFFRHQX1 \product_reg[4] (.RN (rst_n), .CK (clk), .D (n_43), .SI
       (product[3]), .SE (SE), .Q (product[4]));
  SDFFRHQX1 \product_reg[6] (.RN (rst_n), .CK (clk), .D (n_41), .SI
       (product[5]), .SE (SE), .Q (product[6]));
  OAI21X1 g3292__5122(.A0 (scan_out), .A1 (n_66), .B0 (n_9), .Y (n_94));
  SDFFRHQX1 \product_reg[15] (.RN (rst_n), .CK (clk), .D (n_39), .SI
       (product[14]), .SE (SE), .Q (product[15]));
  SDFFRHQX1 \product_reg[11] (.RN (rst_n), .CK (clk), .D (n_49), .SI
       (product[10]), .SE (SE), .Q (product[11]));
  SDFFRHQX1 \product_reg[12] (.RN (rst_n), .CK (clk), .D (n_51), .SI
       (product[11]), .SE (SE), .Q (product[12]));
  SDFFRHQX1 \product_reg[14] (.RN (rst_n), .CK (clk), .D (n_37), .SI
       (product[13]), .SE (SE), .Q (product[14]));
  SDFFRHQX1 \product_reg[5] (.RN (rst_n), .CK (clk), .D (n_42), .SI
       (product[4]), .SE (SE), .Q (product[5]));
  SDFFRHQX1 \product_reg[7] (.RN (rst_n), .CK (clk), .D (n_48), .SI
       (product[6]), .SE (SE), .Q (product[7]));
  SDFFRHQX1 \product_reg[1] (.RN (rst_n), .CK (clk), .D (n_46), .SI
       (product[0]), .SE (SE), .Q (product[1]));
  SDFFRHQX1 \product_reg[13] (.RN (rst_n), .CK (clk), .D (n_38), .SI
       (product[12]), .SE (SE), .Q (product[13]));
  SDFFRHQX1 \product_reg[10] (.RN (rst_n), .CK (clk), .D (n_40), .SI
       (product[9]), .SE (SE), .Q (product[10]));
  AOI21XL g3285__7098(.A0 (count[4]), .A1 (n_76), .B0 (n_77), .Y
       (n_92));
  NAND2XL g3300__2346(.A (n_107), .B (n_67), .Y (n_80));
  SDFFRHQX1 done_reg(.RN (rst_n), .CK (clk), .D (n_20), .SI (count[4]),
       .SE (SE), .Q (done));
  NAND2XL g3396__6417(.A (A[8]), .B (n_132), .Y (n_144));
  AOI21X1 g3359__5477(.A0 (n_137), .A1 (n_32), .B0 (n_95), .Y (n_147));
  NOR2XL g3288__2398(.A (count[4]), .B (n_76), .Y (n_77));
  MX2X1 g3386__5107(.A (M[7]), .B (multiplicand[7]), .S0 (n_89), .Y
       (n_75));
  MX2X1 g3387__6260(.A (M[0]), .B (multiplicand[0]), .S0 (n_89), .Y
       (n_74));
  MX2X1 g3388__4319(.A (M[1]), .B (multiplicand[1]), .S0 (n_89), .Y
       (n_73));
  MX2X1 g3389__8428(.A (M[2]), .B (multiplicand[2]), .S0 (n_89), .Y
       (n_72));
  MX2X1 g3390__5526(.A (M[3]), .B (multiplicand[3]), .S0 (n_89), .Y
       (n_71));
  MX2X1 g3391__6783(.A (M[4]), .B (multiplicand[4]), .S0 (n_89), .Y
       (n_70));
  MX2X1 g3392__3680(.A (M[5]), .B (multiplicand[5]), .S0 (n_89), .Y
       (n_69));
  MX2X1 g3393__1617(.A (M[6]), .B (multiplicand[6]), .S0 (n_89), .Y
       (n_68));
  OAI21XL g3309__2802(.A0 (scan_out), .A1 (n_65), .B0 (state[1]), .Y
       (n_67));
  AOI22X1 g3318__1705(.A0 (n_185), .A1 (n_65), .B0 (start), .B1 (n_63),
       .Y (n_66));
  OAI22X1 g3319__5122(.A0 (n_30), .A1 (n_65), .B0 (n_10), .B1 (n_63),
       .Y (n_64));
  MX2X1 g3373__8246(.A (A[0]), .B (product[8]), .S0 (n_50), .Y (n_62));
  MXI2XL g3349__7098(.A (n_15), .B (n_60), .S0 (M[7]), .Y (n_61));
  MXI2XL g3350__6131(.A (n_15), .B (n_60), .S0 (M[4]), .Y (n_59));
  MXI2XL g3351__1881(.A (n_15), .B (n_60), .S0 (M[5]), .Y (n_57));
  MXI2XL g3352__5115(.A (n_15), .B (n_60), .S0 (M[6]), .Y (n_56));
  MXI2XL g3357__7482(.A (n_15), .B (n_60), .S0 (M[0]), .Y (n_55));
  MXI2XL g3348__4733(.A (n_15), .B (n_60), .S0 (M[2]), .Y (n_54));
  MXI2XL g3293__6161(.A (count[3]), .B (n_52), .S0 (n_31), .Y (n_53));
  MX2X1 g3368__9315(.A (A[4]), .B (product[12]), .S0 (n_50), .Y (n_51));
  MX2X1 g3369__9945(.A (A[3]), .B (product[11]), .S0 (n_50), .Y (n_49));
  MX2X1 g3370__2883(.A (Q[8]), .B (product[7]), .S0 (n_50), .Y (n_48));
  MX2X1 g3371__2346(.A (Q[1]), .B (product[0]), .S0 (n_50), .Y (n_47));
  MX2X1 g3372__1666(.A (Q[2]), .B (product[1]), .S0 (n_50), .Y (n_46));
  MXI2XL g3347__7410(.A (n_60), .B (n_15), .S0 (A[8]), .Y (n_142));
  MXI2XL g3346__6417(.A (n_15), .B (n_60), .S0 (M[3]), .Y (n_45));
  MX2X1 g3377__5477(.A (Q[4]), .B (product[3]), .S0 (n_50), .Y (n_44));
  MX2X1 g3378__2398(.A (Q[5]), .B (product[4]), .S0 (n_50), .Y (n_43));
  MX2X1 g3379__5107(.A (Q[6]), .B (product[5]), .S0 (n_50), .Y (n_42));
  MX2X1 g3380__6260(.A (Q[7]), .B (product[6]), .S0 (n_50), .Y (n_41));
  MX2X1 g3381__4319(.A (A[2]), .B (product[10]), .S0 (n_50), .Y (n_40));
  MX2X1 g3382__8428(.A (A[7]), .B (product[15]), .S0 (n_50), .Y (n_39));
  MX2X1 g3383__5526(.A (A[5]), .B (product[13]), .S0 (n_50), .Y (n_38));
  MX2X1 g3384__6783(.A (A[6]), .B (product[14]), .S0 (n_50), .Y (n_37));
  MX2X1 g3385__3680(.A (A[1]), .B (product[9]), .S0 (n_50), .Y (n_36));
  MXI2XL g3345__1617(.A (n_15), .B (n_60), .S0 (M[1]), .Y (n_35));
  INVXL g3404(.A (n_137), .Y (n_34));
  MX2X1 g3374__2802(.A (Q[3]), .B (product[2]), .S0 (n_50), .Y (n_33));
  CLKINVX1 g3405(.A (n_96), .Y (n_132));
  OAI21X1 g3407__1705(.A0 (n_11), .A1 (Q[0]), .B0 (n_15), .Y (n_32));
  NAND2XL g3301__5122(.A (count[3]), .B (n_31), .Y (n_76));
  NAND2XL g3412__8246(.A (state[1]), .B (n_95), .Y (n_96));
  NOR2XL g3411__7098(.A (scan_out), .B (n_30), .Y (n_137));
  MXI2XL g3342__6131(.A (n_28), .B (count[2]), .S0 (n_16), .Y (n_29));
  NAND2XL g3397__7482(.A (count[4]), .B (n_107), .Y (n_25));
  NAND4XL g3375__4733(.A (count[3]), .B (n_24), .C (n_28), .D (n_8), .Y
       (n_65));
  NOR2X1 g3413__6161(.A (state[1]), .B (n_107), .Y (n_89));
  INVXL g3406(.A (n_50), .Y (n_20));
  NOR2XL g3376__6417(.A (n_28), .B (n_16), .Y (n_31));
  CLKINVX1 g3394(.A (n_60), .Y (n_15));
  NAND2X1 g3414__5477(.A (scan_out), .B (n_63), .Y (n_50));
  MXI2XL g3408__2398(.A (count[1]), .B (n_13), .S0 (count[0]), .Y
       (n_14));
  CLKINVX1 g3415(.A (n_185), .Y (n_30));
  CLKINVX1 g3417(.A (n_107), .Y (n_95));
  AND2X1 g3419__6260(.A (Q[0]), .B (n_11), .Y (n_60));
  NAND2XL g3420__4319(.A (state[0]), .B (n_10), .Y (n_107));
  NAND2XL g3422__8428(.A (state[0]), .B (scan_out), .Y (n_9));
  NOR2XL g3424__5526(.A (state[0]), .B (state[1]), .Y (n_63));
  NOR2XL g3421__6783(.A (count[4]), .B (count[1]), .Y (n_8));
  NAND2XL g3423__3680(.A (count[0]), .B (count[1]), .Y (n_16));
  INVXL g3426(.A (A[6]), .Y (n_7));
  INVXL g3432(.A (A[3]), .Y (n_6));
  INVXL g3436(.A (A[2]), .Y (n_5));
  INVXL g3427(.A (A[1]), .Y (n_4));
  INVXL g3431(.A (A[4]), .Y (n_3));
  CLKINVX1 g3435(.A (Q_minus_1), .Y (n_11));
  CLKINVX1 g3430(.A (count[2]), .Y (n_28));
  INVXL g3429(.A (A[5]), .Y (n_1));
  INVXL g3425(.A (Q[8]), .Y (n_0));
  CLKINVX1 g3434(.A (A[0]), .Y (n_85));
  CLKINVX1 g3433(.A (scan_out), .Y (n_10));
  CLKINVX1 g3439(.A (count[0]), .Y (n_24));
  CLKINVX1 g3438(.A (count[3]), .Y (n_52));
  CLKINVX1 g3437(.A (count[1]), .Y (n_13));
  OAI21X1 g2(.A0 (n_96), .A1 (n_92), .B0 (n_25), .Y (n_170));
  AO22XL g3500(.A0 (Q[0]), .A1 (n_132), .B0 (Q_minus_1), .B1 (n_107),
       .Y (n_179));
  OAI22X1 g3501(.A0 (n_53), .A1 (n_96), .B0 (n_52), .B1 (n_95), .Y
       (n_180));
  OAI22X1 g3502(.A0 (n_29), .A1 (n_96), .B0 (n_28), .B1 (n_95), .Y
       (n_181));
  OAI22X1 g3503(.A0 (n_85), .A1 (n_96), .B0 (n_0), .B1 (n_95), .Y
       (n_182));
  OAI22X1 g3504(.A0 (count[0]), .A1 (n_96), .B0 (n_24), .B1 (n_95), .Y
       (n_183));
  OAI22X1 g3505(.A0 (n_14), .A1 (n_96), .B0 (n_13), .B1 (n_95), .Y
       (n_184));
  NOR2BX1 g3506(.AN (state[1]), .B (state[0]), .Y (n_185));
  INVXL g3(.A (n_186), .Y (n_187));
  AOI222XL g3507(.A0 (multiplier[0]), .A1 (n_89), .B0 (Q[1]), .B1
       (n_132), .C0 (Q[0]), .C1 (n_107), .Y (n_186));
  INVXL g3508(.A (n_188), .Y (n_189));
  AOI222XL g3509(.A0 (multiplier[1]), .A1 (n_89), .B0 (Q[2]), .B1
       (n_132), .C0 (Q[1]), .C1 (n_107), .Y (n_188));
  INVXL g3510(.A (n_190), .Y (n_191));
  AOI222XL g3511(.A0 (multiplier[2]), .A1 (n_89), .B0 (Q[3]), .B1
       (n_132), .C0 (Q[2]), .C1 (n_107), .Y (n_190));
  INVXL g3512(.A (n_192), .Y (n_193));
  AOI222XL g3513(.A0 (multiplier[7]), .A1 (n_89), .B0 (Q[8]), .B1
       (n_132), .C0 (Q[7]), .C1 (n_107), .Y (n_192));
  INVXL g3514(.A (n_194), .Y (n_195));
  AOI222XL g3515(.A0 (multiplier[6]), .A1 (n_89), .B0 (Q[7]), .B1
       (n_132), .C0 (Q[6]), .C1 (n_107), .Y (n_194));
  INVXL g3516(.A (n_196), .Y (n_197));
  AOI222XL g3517(.A0 (multiplier[5]), .A1 (n_89), .B0 (Q[6]), .B1
       (n_132), .C0 (Q[5]), .C1 (n_107), .Y (n_196));
  INVXL g3518(.A (n_198), .Y (n_199));
  AOI222XL g3519(.A0 (multiplier[4]), .A1 (n_89), .B0 (Q[5]), .B1
       (n_132), .C0 (Q[4]), .C1 (n_107), .Y (n_198));
  INVXL g3520(.A (n_200), .Y (n_201));
  AOI222XL g3521(.A0 (multiplier[3]), .A1 (n_89), .B0 (Q[4]), .B1
       (n_132), .C0 (Q[3]), .C1 (n_107), .Y (n_200));
endmodule

