
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  2 2025 17:46:36 IST (Sep  2 2025 12:16:36 UTC)

// Verification Directory fv/d_ff 

module d_ff(D, clk, Q, Q_bar, SE, scan_in, scan_out);
  input D, clk, SE, scan_in;
  output Q, Q_bar, scan_out;
  wire D, clk, SE, scan_in;
  wire Q, Q_bar, scan_out;
  wire R_wire;
  sr_ff UUT_sr_ff(.S (D), .R (R_wire), .clk (clk), .Q (Q), .Q_bar
       (Q_bar));
  INVXL g3(.A (D), .Y (R_wire));
endmodule

