
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  2 2025 16:34:51 IST (Sep  2 2025 11:04:51 UTC)

// Verification Directory fv/sync_FA 

module sync_FA(a, b, cin, clk, sum, cout, SE, scan_in, scan_out);
  input a, b, cin, clk, SE, scan_in;
  output sum, cout, scan_out;
  wire a, b, cin, clk, SE, scan_in;
  wire sum, cout, scan_out;
  wire c1_wire, c2_wire, n_0, s1_wire, sum_w;
  assign scan_out = sum;
  sync_HA ha1(.a (a), .b (b), .clk (clk), .sum (s1_wire), .c_out
       (c1_wire));
  sync_HA ha2(.a (s1_wire), .b (cin), .clk (clk), .sum (sum_w), .c_out
       (c2_wire));
  SDFFQXL cout_reg(.CK (clk), .D (n_0), .SI (scan_in), .SE (SE), .Q
       (cout));
  SDFFQXL sum_reg(.CK (clk), .D (sum_w), .SI (cout), .SE (SE), .Q
       (sum));
  OR2X1 g17__2398(.A (c1_wire), .B (c2_wire), .Y (n_0));
endmodule

