
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  2 2025 17:41:25 IST (Sep  2 2025 12:11:25 UTC)

// Verification Directory fv/decoder 

module decoder(y, a, clk, rst, SE, scan_in, scan_out);
  input [2:0] a;
  input clk, rst, SE, scan_in;
  output [7:0] y;
  output scan_out;
  wire [2:0] a;
  wire clk, rst, SE, scan_in;
  wire [7:0] y;
  wire scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  assign scan_out = y[7];
  SDFFQX1 \y_reg[4] (.CK (clk), .D (n_13), .SI (y[3]), .SE (SE), .Q
       (y[4]));
  SDFFQX1 \y_reg[6] (.CK (clk), .D (n_4), .SI (y[5]), .SE (SE), .Q
       (y[6]));
  SDFFQX1 \y_reg[7] (.CK (clk), .D (n_10), .SI (y[6]), .SE (SE), .Q
       (y[7]));
  SDFFQX1 \y_reg[0] (.CK (clk), .D (n_2), .SI (scan_in), .SE (SE), .Q
       (y[0]));
  SDFFQX1 \y_reg[3] (.CK (clk), .D (n_12), .SI (y[2]), .SE (SE), .Q
       (y[3]));
  SDFFQX1 \y_reg[5] (.CK (clk), .D (n_11), .SI (y[4]), .SE (SE), .Q
       (y[5]));
  SDFFQX1 \y_reg[2] (.CK (clk), .D (n_5), .SI (y[1]), .SE (SE), .Q
       (y[2]));
  SDFFQX1 \y_reg[1] (.CK (clk), .D (n_7), .SI (y[0]), .SE (SE), .Q
       (y[1]));
  NOR2XL g188__2398(.A (rst), .B (n_1), .Y (n_13));
  NOR3XL g189__5107(.A (a[2]), .B (rst), .C (n_8), .Y (n_12));
  NOR3X1 g192__6260(.A (rst), .B (n_9), .C (n_6), .Y (n_11));
  NOR3XL g193__4319(.A (rst), .B (n_9), .C (n_8), .Y (n_10));
  NOR3X1 g187__8428(.A (a[2]), .B (rst), .C (n_6), .Y (n_7));
  NOR3X1 g186__5526(.A (a[2]), .B (rst), .C (n_3), .Y (n_5));
  NOR3X1 g190__6783(.A (rst), .B (n_9), .C (n_3), .Y (n_4));
  NOR3BXL g191__3680(.AN (n_0), .B (a[2]), .C (rst), .Y (n_2));
  NAND2XL g194__1617(.A (a[2]), .B (n_0), .Y (n_1));
  NAND2BX1 g195__2802(.AN (a[0]), .B (a[1]), .Y (n_3));
  NAND2XL g196__1705(.A (a[0]), .B (a[1]), .Y (n_8));
  NOR2XL g197__5122(.A (a[0]), .B (a[1]), .Y (n_0));
  NAND2BX1 g198__8246(.AN (a[1]), .B (a[0]), .Y (n_6));
  CLKINVX1 g199(.A (a[2]), .Y (n_9));
endmodule

