
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  2 2025 17:37:34 IST (Sep  2 2025 12:07:34 UTC)

// Verification Directory fv/mux 

module mux(a, b, s, clk, rst, y, SE, scan_in, scan_out);
  input a, b, s, clk, rst, SE, scan_in;
  output y, scan_out;
  wire a, b, s, clk, rst, SE, scan_in;
  wire y, scan_out;
  wire n_0, n_1;
  assign scan_out = y;
  SDFFRHQX1 y_reg(.RN (n_0), .CK (clk), .D (n_1), .SI (scan_in), .SE
       (SE), .Q (y));
  MX2X1 g31__2398(.A (a), .B (b), .S0 (s), .Y (n_1));
  INVXL g32(.A (rst), .Y (n_0));
endmodule

