
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 11 2025 13:18:31 IST (Aug 11 2025 07:48:31 UTC)

// Verification Directory fv/seq_det_0010 

module seq_det_0010(clk, rst_n, in, out);
  input clk, rst_n, in;
  output out;
  wire clk, rst_n, in;
  wire out;
  wire [2:0] current_state;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10;
  DFFRHQX1 \current_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_10), .Q
       (current_state[1]));
  DFFRHQX1 \current_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_9), .Q
       (current_state[0]));
  OAI21X1 g257__2398(.A0 (current_state[1]), .A1 (n_7), .B0 (n_8), .Y
       (n_10));
  OAI32X1 g259__5107(.A0 (in), .A1 (current_state[2]), .A2 (n_2), .B0
       (n_0), .B1 (n_8), .Y (n_9));
  AOI21X1 g261__6260(.A0 (current_state[2]), .A1 (n_1), .B0 (n_5), .Y
       (n_7));
  AND2XL g260__4319(.A (current_state[1]), .B (n_5), .Y (n_6));
  NAND3BX1 g263__8428(.AN (current_state[0]), .B (current_state[1]), .C
       (n_3), .Y (n_8));
  NOR2XL g262__5526(.A (n_3), .B (n_2), .Y (out));
  NOR3BX1 g264__6783(.AN (current_state[0]), .B (in), .C
       (current_state[2]), .Y (n_5));
  NOR2XL g265__3680(.A (in), .B (current_state[0]), .Y (n_1));
  OR2XL g266__1617(.A (current_state[0]), .B (current_state[1]), .Y
       (n_2));
  CLKINVX1 g267(.A (in), .Y (n_0));
  DFFRX1 \current_state_reg[2] (.RN (rst_n), .CK (clk), .D (n_6), .Q
       (current_state[2]), .QN (n_3));
endmodule

