
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 11 2025 12:39:24 IST (Aug 11 2025 07:09:24 UTC)

// Verification Directory fv/sr_ff 

module sr_ff(S, R, clk, Q, Q_bar);
  input S, R, clk;
  output Q, Q_bar;
  wire S, R, clk;
  wire Q, Q_bar;
  wire n_0, n_1, n_2;
  SDFFQX1 Q_reg(.CK (clk), .D (n_1), .SI (Q), .SE (n_2), .Q (Q));
  SDFFQXL Q_bar_reg(.CK (clk), .D (R), .SI (n_0), .SE (n_2), .Q
       (Q_bar));
  NOR2XL g25__2398(.A (R), .B (S), .Y (n_2));
  CLKINVX1 g26(.A (R), .Y (n_1));
  INVXL g27(.A (Q), .Y (n_0));
endmodule

