
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug  4 2025 09:34:16 IST (Aug  4 2025 04:04:16 UTC)

// Verification Directory fv/sync_HA 

module sync_HA(a, b, clk, sum, c_out);
  input a, b, clk;
  output sum, c_out;
  wire a, b, clk;
  wire sum, c_out;
  wire n_0, n_1;
  DFFQXL sum_reg(.CK (clk), .D (n_1), .Q (sum));
  DFFQXL c_out_reg(.CK (clk), .D (n_0), .Q (c_out));
  ADDHXL g42__2398(.A (b), .B (a), .CO (n_0), .S (n_1));
endmodule

