
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 11 2025 12:46:24 IST (Aug 11 2025 07:16:24 UTC)

// Verification Directory fv/d_ff 

module d_ff(D, clk, Q, Q_bar);
  input D, clk;
  output Q, Q_bar;
  wire D, clk;
  wire Q, Q_bar;
  wire R_wire;
  sr_ff_d UUT_sr_ff_d(.S (D), .R (R_wire), .clk (clk), .Q (Q), .Q_bar
       (Q_bar));
  INVXL g3(.A (D), .Y (R_wire));
endmodule

