
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 11 2025 13:03:24 IST (Aug 11 2025 07:33:24 UTC)

// Verification Directory fv/mux 

module mux(a, b, s, clk, rst, y);
  input a, b, s, clk, rst;
  output y;
  wire a, b, s, clk, rst;
  wire y;
  wire n_0;
  SDFFRHQX1 y_reg(.RN (n_0), .CK (clk), .D (a), .SI (b), .SE (s), .Q
       (y));
  INVXL g31(.A (rst), .Y (n_0));
endmodule

