
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep  2 2025 17:44:27 IST (Sep  2 2025 12:14:27 UTC)

// Verification Directory fv/seq_det_0010 

module seq_det_0010(clk, rst_n, in, out, SE, scan_in, scan_out);
  input clk, rst_n, in, SE, scan_in;
  output out, scan_out;
  wire clk, rst_n, in, SE, scan_in;
  wire out, scan_out;
  wire [2:0] current_state;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10;
  SDFFRHQX1 \current_state_reg[1] (.RN (rst_n), .CK (clk), .D (n_10),
       .SI (current_state[0]), .SE (SE), .Q (current_state[1]));
  SDFFRHQX1 \current_state_reg[0] (.RN (rst_n), .CK (clk), .D (n_9),
       .SI (scan_in), .SE (SE), .Q (current_state[0]));
  SDFFRHQX1 \current_state_reg[2] (.RN (rst_n), .CK (clk), .D (n_6),
       .SI (current_state[1]), .SE (SE), .Q (scan_out));
  OAI21X1 g257__2398(.A0 (current_state[1]), .A1 (n_7), .B0 (n_8), .Y
       (n_10));
  OAI32X1 g259__5107(.A0 (in), .A1 (scan_out), .A2 (n_3), .B0 (n_0),
       .B1 (n_8), .Y (n_9));
  AOI21X1 g261__6260(.A0 (scan_out), .A1 (n_1), .B0 (n_5), .Y (n_7));
  AND2X1 g260__4319(.A (current_state[1]), .B (n_5), .Y (n_6));
  NOR2XL g262__8428(.A (n_2), .B (n_3), .Y (out));
  NAND3BX1 g263__5526(.AN (current_state[0]), .B (current_state[1]), .C
       (n_2), .Y (n_8));
  NOR3BX1 g264__6783(.AN (current_state[0]), .B (in), .C (scan_out), .Y
       (n_5));
  NOR2XL g265__3680(.A (in), .B (current_state[0]), .Y (n_1));
  OR2XL g266__1617(.A (current_state[0]), .B (current_state[1]), .Y
       (n_3));
  CLKINVX1 g267(.A (in), .Y (n_0));
  CLKINVX1 g268(.A (scan_out), .Y (n_2));
endmodule

